function templates = pipelineTemplates()
% PIPELINETEMPLATES  Return all built-in pipeline templates.
%
%   templates = PIPELINETEMPLATES() returns a struct array where each
%   element describes one template:
%
%     .name      - display name (shown in the picker dialog)
%     .steps     - cell array of step label strings; must match stepRegistry
%                  names exactly (and therefore the StepsListBox items)
%     .overrides - cell array of structs, one per step, containing raw
%                  EEGLAB parameter key→value overrides to apply on top of
%                  the step defaults.  Use struct() for no overrides.
%
%   Adding a template: append one block below following the existing
%   pattern and ensure every step name matches an entry in stepRegistry.
%
%   See also: stepRegistry, nestapp

templates = struct('name', {}, 'steps', {}, 'overrides', {});

%% ---- TMS-EEG / TEP (TESA) -----------------------------------------------
t = blankTemplate();
t.name = 'TMS-EEG / TEP (TESA)';
t.steps = { ...
    'Load Data', ...
    'Load Channel Location', ...
    'Remove un-needed Channels', ...
    'Find TMS Pulses (TESA)', ...
    'Remove TMS Artifacts (TESA)', ...
    'Interpolate Missing Data (TESA)', ...
    'Re-Sample', ...
    'Frequency Filter (TESA)', ...
    'Epoching', ...
    'Remove Bad Channels', ...
    'Interpolate Channels', ...
    'Run TESA ICA', ...
    'Remove ICA Components (TESA)', ...
    'Remove Baseline', ...
    'Remove Bad Epoch', ...
    'Save New Set'};
% All step defaults already match standard TESA best-practice settings;
% no overrides needed.
t.overrides = repmat({struct()}, 1, numel(t.steps));
templates(end+1) = t;

%% ---- Resting-State EEG --------------------------------------------------
t = blankTemplate();
t.name = 'Resting-State EEG';
t.steps = { ...
    'Load Data', ...
    'Load Channel Location', ...
    'Frequency Filter', ...
    'Frequency Filter (CleanLine)', ...
    'Remove Bad Channels', ...
    'Interpolate Channels', ...
    'Re-Reference', ...
    'Run ICA', ...
    'Label ICA Components', ...
    'Flag ICA Components for Rejection', ...
    'Remove Flagged ICA Components', ...
    'Epoching', ...
    'Remove Bad Epoch', ...
    'Save New Set'};
% Override defaults for resting-state conventions
ov = repmat({struct()}, 1, numel(t.steps));
ov{3}.locutoff = 0.5;   % HPF at 0.5 Hz instead of 1 Hz
ov{3}.hicutoff = 40;    % LPF at 40 Hz instead of 80 Hz
ov{7}.ref      = '[]';  % average reference (empty = average in EEGLAB)
ov{12}.timelim = [-1 1]; % 2-second epochs
t.overrides = ov;
templates(end+1) = t;

%% ---- Minimal (HPF + bad channel removal) --------------------------------
t = blankTemplate();
t.name = 'Minimal (HPF + bad channels)';
t.steps = { ...
    'Load Data', ...
    'Load Channel Location', ...
    'Frequency Filter', ...
    'Remove Bad Channels', ...
    'Interpolate Channels', ...
    'Save New Set'};
% HPF at 0.5 Hz; no ICA, no epoching, no re-referencing
ov = repmat({struct()}, 1, numel(t.steps));
ov{3}.locutoff = 0.5;
t.overrides = ov;
templates(end+1) = t;

end

%% ---- helpers ---------------------------------------------------------------

function t = blankTemplate()
t = struct('name', '', 'steps', {{}}, 'overrides', {{}});
end
