
% SPDX-License-Identifier: GPL-3.0-or-later
% Copyright (C) 2023-2026 Aref Pariz and Wesley Dunne.
% Part of nestapp; see the LICENSE file for full terms.
function citation = templateCitation(pipelineName)
% TEMPLATECITATION  Return the citation block for a built-in template.
%   citation = TEMPLATECITATION(pipelineName) returns a struct with
%   fields .doi, .reference, .notes; or an empty struct if the pipeline
%   name does not match a built-in template that has a citation registered.
%
%   Adding citations here is the single source of truth used by
%   runPipelineCore to print attribution to the batch log.

citation = struct('doi', '', 'reference', '', 'notes', '');

if isempty(pipelineName)
    return
end

if contains(pipelineName, 'ARTIST', 'IgnoreCase', true)
    citation.doi = '10.1002/hbm.23938';
    citation.reference = ['Wu W. et al. (2018). ARTIST: A fully automated artifact ' ...
        'rejection algorithm for single-pulse TMS-EEG data. ' ...
        'Hum Brain Mapp 39(4):1607-1625.'];
    citation.notes = ['Note: ARTIST''s 23-feature FLDA IC classifier is not ' ...
        'publicly distributed. This template substitutes TESA pop_tesa_compselect ' ...
        'for stage-3 IC classification - also cite Rogasch et al. (2017) ' ...
        'NeuroImage 147:934-951 (doi:10.1016/j.neuroimage.2017.06.014). ' ...
        'The rest of the pipeline geometry and parameters follow Wu 2018 verbatim.'];

elseif contains(pipelineName, 'AARATEP', 'IgnoreCase', true)
    citation.doi = '10.1109/NER49283.2021.9441147';
    citation.reference = ['Cline C.C. et al. (2021). Advanced Artifact Removal ' ...
        'for Automated TMS-EEG Data Processing. IEEE NER.'];
    citation.notes = ['Also cite Rogasch et al. (2017) NeuroImage 147:934-951 ' ...
        '(TESA, doi:10.1016/j.neuroimage.2017.06.014) and ' ...
        'Mutanen et al. (2018) NeuroImage 166:135-151 ' ...
        '(SOUND, doi:10.1016/j.neuroimage.2017.10.021). ' ...
        'Helpers vendored from chriscline/AARATEPPipeline (MIT) ' ...
        'under third_party/aaratep/. See THIRD_PARTY_NOTICES.md.'];

elseif contains(pipelineName, 'TESA', 'IgnoreCase', true)
    citation.doi = '10.1016/j.neuroimage.2017.06.014';
    citation.reference = ['Rogasch N.C. et al. (2017). Analysing concurrent ' ...
        'transcranial magnetic stimulation and electroencephalographic data: ' ...
        'a review and introduction to the open-source TESA software. ' ...
        'NeuroImage 147:934-951.'];
    citation.notes = ['If your pipeline includes Remove Recording Noise (SOUND), ' ...
        'also cite Mutanen et al. (2018) NeuroImage 166:135-151 ' ...
        '(doi:10.1016/j.neuroimage.2017.10.021).'];

elseif contains(pipelineName, 'Resting', 'IgnoreCase', true)
    citation.doi = '10.1038/s41598-023-27528-0';
    citation.reference = ['Delorme A. (2023). EEG is better left alone. ' ...
        'Sci Rep 13:2372. (Pipeline based on PREP, Bigdely-Shamlo 2015.)'];

elseif contains(pipelineName, 'Minimal', 'IgnoreCase', true)
    citation.doi = '10.1038/s41598-023-27528-0';
    citation.reference = ['Delorme A. (2023). EEG is better left alone. ' ...
        'Sci Rep 13:2372.'];
end
end
